
-- Adresse
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('884-5277 Non Ave','Placanica','57283'),('Ap #310-8385 Semper. Ave','Banda','95527'),('P.O. Box 508, 2794 In Av.','Susegana','48390'),('P.O. Box 650, 3412 Metus. St.','Negrete','97101'),('609-5313 Donec Street','Proddatur','49493'),('P.O. Box 914, 8708 Nec Ave','Velletri','66840'),('2694 Sodales Rd.','Burin','27356'),('260-2835 Metus St.','Aix-en-Provence','84621'),('P.O. Box 876, 6750 Id Rd.','Belford Roxo','03866'),('Ap #189-479 Fermentum Ave','Pickering','86500');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('698-3213 Nisl. Road','San Giuliano di Puglia','30470'),('Ap #143-2566 Nisi Road','Cuddapah','52207'),('P.O. Box 842, 2764 Rutrum Rd.','Tongerlo','18458'),('2644 Lorem. Avenue','Dorchester','15990'),('P.O. Box 193, 3267 Mauris Rd.','Cabano','08610'),('P.O. Box 404, 8452 Non Av.','Kanchipuram','67814'),('P.O. Box 873, 1522 Risus Avenue','Burcht','86709'),('Ap #912-1387 Lectus Ave','Fort Simpson','57709'),('P.O. Box 986, 8797 Iaculis Ave','Purnea','53943'),('Ap #742-1339 At Street','Purnea','61806');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('P.O. Box 906, 8038 Id, St.','Lacombe County','56707'),('P.O. Box 391, 1524 Vitae, St.','Introd','95775'),('9857 Integer Rd.','Bonnyville','03646'),('8253 Purus. St.','Hamilton','72737'),('308-5139 Erat Ave','Deventer','68816'),('Ap #227-4126 In, Ave','Carnoustie','66244'),('Ap #191-3107 Luctus Av.','Hamilton','42450'),('Ap #802-4517 Nam St.','Bellevue','54925'),('P.O. Box 459, 1059 Nibh. Road','Curridabat','22555'),('180-5428 Integer Rd.','Notre-Dame-de-la-Salette','32872');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('Ap #701-7719 Adipiscing, Ave','Honolulu','18180'),('9447 Elit. Rd.','Macclesfield','53713'),('990-5692 Mus. Rd.','Obaix','26392'),('154-9187 Sed Ave','Turnhout','23746'),('127-3034 Vivamus Ave','Inuvik','36848'),('335-5188 Sed St.','Meer','40962'),('413-429 Enim. Rd.','Gagliano del Capo','76891'),('Ap #721-6374 Est, Street','North Cowichan','89934'),('Ap #401-2195 Dignissim St.','Palmerston North','07860'),('Ap #906-4312 Montes, Av.','Zwickau','95011');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('668-5625 Amet, Rd.','Girona','11325'),('Ap #121-7550 Ipsum Rd.','Santomenna','17267'),('P.O. Box 262, 6894 Mi Street','Francofonte','36568'),('7741 Urna. Street','San Esteban','55404'),('9097 Vulputate Ave','Dégelis','25333'),('P.O. Box 864, 8246 Aptent St.','Grezzana','57296'),('Ap #123-2925 Adipiscing Rd.','La Cruz','57600'),('P.O. Box 148, 6139 A Av.','Tucson','61455'),('Ap #979-2764 Dui. Rd.','Wolverhampton','84673'),('Ap #717-8175 Sagittis Rd.','Bolzano/Bozen','37248');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('596-9792 Ligula. Ave','Holyhead','85655'),('7616 Velit Road','Baunatal','67747'),('968-5170 Donec Avenue','Sikar','31750'),('P.O. Box 166, 4496 A, Rd.','Shawville','78786'),('490-6874 Aliquet St.','Chiusa Sclafani','35393'),('5113 Fusce Road','Piegaro','97018'),('Ap #557-565 Euismod Av.','Vandoies/Vintl','13667'),('Ap #661-4210 Fusce Road','Fermont','67535'),('857-3726 Cras Road','Huechuraba','53343'),('6522 Ac Rd.','Panguipulli','19263');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('P.O. Box 913, 987 Phasellus Road','Pretoro','26547'),('8505 Aliquet Rd.','Bolzano/Bozen','16460'),('5066 Sollicitudin Ave','Champdani','06780'),('Ap #513-8133 Enim, St.','Augusta','77554'),('P.O. Box 480, 2726 Iaculis Ave','Auvelais','64659'),('6423 Non Road','Valtournenche','99887'),('P.O. Box 132, 2846 Ut Rd.','Bilbo','36201'),('P.O. Box 495, 5389 Pede, Rd.','Champorcher','65560'),('P.O. Box 126, 5132 Ultrices Av.','Forbach','73722'),('1391 Sed Rd.','Malloa','84823');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('8729 Et Rd.','Moorsele','97163'),('5824 Mauris Avenue','Avise','81461'),('932-4637 Maecenas St.','Kamoke','55018'),('980-9257 Dis Road','Villafalletto','02354'),('8330 Sagittis Rd.','Meerdonk','52829'),('P.O. Box 206, 4560 Et Street','Speyer','33463'),('Ap #165-7653 Vitae St.','Großpetersdorf','50363'),('2748 Sit Rd.','Bridgnorth','99177'),('7345 Lobortis Av.','Nanaimo','42588'),('P.O. Box 910, 5207 Donec Av.','Fredericton','19440');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('2031 Sed Ave','Gijón','40776'),('5475 Nunc Road','Chiguayante','42946'),('3414 Dictum Avenue','Fayetteville','57109'),('Ap #104-8555 Massa. Road','Lauregno/Laurein','07841'),('597-4372 Et, Rd.','Liberchies','08170'),('584-8612 Elementum Av.','Neumünster','43028'),('6442 Tristique Rd.','Cañas','37451'),('579-6940 Pede St.','Dessel','73588'),('653-9656 Et, Av.','Dawson Creek','99587'),('Ap #461-958 Facilisis Street','Belgrade','42908');
INSERT INTO ocpizza.adresse (rue,ville,code_postal) VALUES ('741-6988 Pellentesque, Avenue','Langholm','94380'),('Ap #764-8609 Nullam Av.','Rouyn-Noranda','98629'),('181-1231 Integer Avenue','Riparbella','14530'),('3066 Integer St.','Terzorio','60745'),('814-1956 Aptent Road','Bareilly','10105'),('8020 Scelerisque Road','Lota','25089'),('P.O. Box 283, 9860 Dui Street','Zutphen','06683'),('9115 Dolor, Road','Nossegem','46983'),('994-1632 Nulla St.','Tulln an der Donau','37837'),('250-1972 Placerat, Rd.','Herenthout','09156');


-- Client
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Bianca','Horne',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Shaine','Terry',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Brock','Blankenship',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Sylvester','Zimmerman',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Brittany','Rosario',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Ferdinand','Wyatt',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Justin','Ramirez',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Justina','Clemons',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Kelsie','Delgado',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Beatrice','Mccall',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Kelsey','Lee',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Riley','Browning',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Martha','Foreman',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Dorian','Ferrell',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Dillon','Gamble',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Tarik','Robbins',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Michelle','Vaughan',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Macey','Quinn',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Dillon','Bond',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Norman','Ashley',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Odessa','Koch',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Illiana','Kerr',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Madison','Carpenter',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Dante','Oliver',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Ariel','Hodges',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Anne','Scott',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Libby','Hartman',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Halla','Weeks',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Regina','Ferrell',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Yuri','Lynn',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Sharon','Norman',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Amir','Mason',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Karina','Rojas',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Leroy','Bennett',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Halla','Greer',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Bree','Blanchard',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Jasper','Battle',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Merritt','Donaldson',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Reuben','Carey',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Aurora','Dodson',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Kelsie','Colon',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Reagan','Cruz',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Bruno','Whitney',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Amy','Church',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Vernon','Jennings',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Forrest','Sanford',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Hammett','Santana',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Upton','Nolan',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Uriah','Kirk',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Mohammad','Fitzgerald',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Grant','Cobb',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Patience','Cobb',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'clio','Torres',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Abigail','Riley',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Maxine','Poole',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Merrill','Ochoa',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Shellie','Atkins',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Hamilton','Hicks',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Deanna','Roth',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Eaton','Golden',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Odette','Becker',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Quail','Murphy',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Victoria','Atkinson',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Shelly','Perez',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Merrill','Harrington',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Keaton','Carter',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Sydney','Fry',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Amena','Phillips',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Kirestin','Mcmahon',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Whilemina','Castillo',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Lucy','Rosario',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Keegan','Holloway',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Chava','Fletcher',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Nero','Lester',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Quintessa','Bass',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Rhona','Walker',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Phelan','Casey',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Madeline','Bryant',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Beatrice','Massey',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Forrest','Irwin',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'India','Ball',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Jerome','Crosby',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Kyla','Fry',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Samuel','Watts',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Honorato','Blake',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Maryam','Brown',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Yardley','Peck',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Amela','Pace',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Stephen','Rojas',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Cheryl','Webster',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);
INSERT INTO ocpizza.client (prenom_client,nom_client,id_adresse) (SELECT 'Justina','Dillon',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Montana','Benjamin',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Britanney','Hughes',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Malcolm','Wong',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Cassandra','Vang',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Rahim','Salinas',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Moses','Horne',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Scott','Gay',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Fritz','Dickerson',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Asher','Cobb',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);

-- Pizza
INSERT INTO ocpizza.pizza (nom_pizza,prix_pizza) VALUES ('Margarita','5'),('Salami','6'),('4 Fromages','6.5'),('Végétarienne','6'),('Calzone','7'),('Rucola','8'),('Saumon','8.5'),('Capres','6.5'),('4 Saisons','7.5');

-- Ingredient
INSERT INTO ocpizza.ingredient (nom_ingredient,quantiteu_ingredient,seuil_ingredient) VALUES ('Sauce Tomates','L','1'),('Fromage rapé','kg','1'),('Salami','g','100'),('Gorgonzola','kg','0.2'),('Mozzarella','kg','0.2'),('Chèvre','kg','0.1'),('Courgette','g','110'),('Oignon','g','75'),('Aubergine','g','100'),('Oeuf','u','3');
INSERT INTO ocpizza.ingredient (nom_ingredient,quantiteu_ingredient,seuil_ingredient) VALUES ('Roquette','g','20'),('Saumon','g','10.2'),('Capres','g','50'),('Champignons','g','70'),('Pâte','kg','1.5');

-- Restaurant
INSERT INTO ocpizza.restaurant (nom_restaurant,id_adresse) (SELECT 'Pizzeria Nonina',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Pizzeria Marina',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Pizzeria Leana',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Pizzeria Angela',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1) UNION (SELECT 'Pizzeria Madona',id_adresse FROM ocpizza.adresse ORDER BY random() LIMIT 1);

-- Stock
-- Pizzeria Nonina
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '30' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Sauce Tomates') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '4' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Fromage rapé') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '600' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Salami') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '2' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Gorgonzola') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '2' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Mozzarella') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '1.5' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Chèvre') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '700' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Courgette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '300' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oignon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '700' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Aubergine') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '50' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oeuf') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r);
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '250' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Roquette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant,'750' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Saumon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '400' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Capres') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '500' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Champignons') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r union SELECT i.id_ingredient, r.id_restaurant, '20' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Pâte') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r);
-- Pizzeria Marina
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '25' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Sauce Tomates') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '3' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Fromage rapé') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '400' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Salami') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '1' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Gorgonzola') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '1' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Mozzarella') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '0.5' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Chèvre') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '400' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Courgette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '100' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oignon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '300' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Aubergine') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '30' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oeuf') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r);
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '100' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Roquette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '250' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Saumon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '200' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Capres') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '300' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Champignons') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r union SELECT i.id_ingredient, r.id_restaurant, '10' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Pâte') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r);
-- Pizzeria Leana
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '35' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Sauce Tomates') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '5' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Fromage rapé') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '400' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Salami') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '3' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Gorgonzola') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '3' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Mozzarella') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '2.5' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Chèvre') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '900' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Courgette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '400' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oignon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '700' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Aubergine') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '45' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oeuf') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r);
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '300' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Roquette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '400' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Saumon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '600' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Capres') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '600' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Champignons') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT i.id_ingredient, r.id_restaurant, '25' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Pâte') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r);
-- Pizzeria Angela
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '28' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Sauce Tomates') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '3.5' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Fromage rapé') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '800' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Salami') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '3' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Gorgonzola') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '2' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Mozzarella') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '2' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Chèvre') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '450' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Courgette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '250' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oignon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '450' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Aubergine') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '38' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oeuf') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r);
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '175' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Roquette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '630' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Saumon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '250' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Capres') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '350' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Champignons') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT i.id_ingredient, r.id_restaurant, '28' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Pâte') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r);
-- Pizzeria Madona
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '32' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Sauce Tomates') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '4' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Fromage rapé') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '650' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Salami') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '2' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Gorgonzola') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '2' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Mozzarella') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '1.8' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Chèvre') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '525' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Courgette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '315' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oignon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '510' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Aubergine') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '42' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Oeuf') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r);
INSERT INTO ocpizza.stock (id_ingredient,id_restaurant,quantite_stock) (SELECT i.id_ingredient, r.id_restaurant, '320' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Roquette') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '680' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Saumon') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '330' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Capres') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '450' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Champignons') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT i.id_ingredient, r.id_restaurant, '32' from (select id_ingredient from ocpizza.ingredient WHERE nom_ingredient='Pâte') as i cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r);

-- Compte
INSERT INTO ocpizza.compte (email,mdp) VALUES ('znelson@ocpizza.com','HXA98KOU4AY'),('rsimmons@ocpizza.com','RZP70PUO5OJ'),('wstark@ocpizza.com','RNJ40QMQ4FN'),('mklein@ocpizza.com','EUF87QWZ7AG'),('hpetersen@ocpizza.com','ELX21AXD5DT'),('nwalls@ocpizza.com','PNR99QDX6LV'),('wballard@ocpizza.com','ESR95LJV2LY'),('gbanks@ocpizza.com','UFF93NTO0KY'),('xbonner@ocpizza.com','WUH47UYP3SU'),('ashields@ocpizza.com','PGH94JIM1WD');
INSERT INTO ocpizza.compte (email,mdp) VALUES ('sbarton@ocpizza.com','FKJ47TBW5LD'),('kmorin@ocpizza.com','MCR58UVE2LN'),('phicks@ocpizza.com','XVT59ZHX1BM'),('opickett@ocpizza.com','QKD36SOF5ZP'),('glynch@ocpizza.com','YEE89NTJ9MQ'),('gdillard@ocpizza.com','UVS81XQX7VR'),('vorr@ocpizza.com','JYN70TDD5WQ'),('kgentry@ocpizza.com','RPT49DZJ1TC'),('dacevedo@ocpizza.com','PCW50QMG9TF'),('dlowery@ocpizza.com','TIQ36SDP1CD');

-- Employe
INSERT INTO ocpizza.employe (type_employee,prenom_employee,nom_employee,id_compte,id_restaurant) 
(SELECT 'Pizzaiolo','Zahir','Nelson', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='znelson@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r 
union SELECT 'Vendeur','Rosalyn','Simmons', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='rsimmons@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r 
union SELECT 'Livreur','Wynne','Stark', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='wstark@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r 
union SELECT 'Gestionnaire cmd','Maxine','Klein', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='mklein@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Nonina') as r 
union SELECT 'Pizzaiolo','Hilel','Petersen', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='hpetersen@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r 
union SELECT 'Vendeur','Nissim','Walls', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='nwalls@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r 
union SELECT 'Livreur','Wing','Ballard', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='wballard@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r 
union SELECT 'Gestionnaire cmd','Guinevere','Banks', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='gbanks@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Marina') as r 
union SELECT 'Pizzaiolo','Xandra','Bonner', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='xbonner@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r 
union SELECT 'Vendeur','Anthony','Shields', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='ashields@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r);
INSERT INTO ocpizza.employe (type_employee,prenom_employee,nom_employee,id_compte,id_restaurant) (SELECT 'Livreur','Serena','Barton', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='sbarton@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT 'Gestionnaire cmd','Kristen','Morin', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='kmorin@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Leana') as r union SELECT 'Pizzaiolo','Perry','Hicks', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='phicks@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT 'Vendeur','Ocean','Pickett', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='opickett@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT 'Livreur','Guinevere','Lynch', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='glynch@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT 'Gestionnaire cmd','Giacomo','Dillard', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='gdillard@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Angela') as r union SELECT 'Pizzaiolo','Vladimir','Orr', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='vorr@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT 'Vendeur','Kibo','Gentry', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='kgentry@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT 'Livreur','Dara','Acevedo', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='dacevedo@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r union SELECT 'Gestionnaire cmd','Dalton','Lowery', c.id_compte, r.id_restaurant from (select id_compte from ocpizza.compte WHERE email='dlowery@ocpizza.com') as c cross join (SELECT id_restaurant FROM ocpizza.restaurant WHERE nom_restaurant='Pizzeria Madona') as r);

-- Recette
-- Margarita
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Margarita') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Margarita') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Margarita') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i);
-- Salami
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Salami') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Salami') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Salami') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Salami') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Salami') as i);
-- 4 Fromages
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Fromages') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Fromages') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Fromages') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Fromages') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Gorgonzola') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Fromages') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Mozzarella') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Fromages') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Chèvre') as i);
-- Végétarienne 
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Végétarienne') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Végétarienne') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Végétarienne') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Végétarienne') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Courgette') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Végétarienne') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Oignon') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Végétarienne') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Aubergine') as i);
-- Calzone
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Calzone') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Calzone') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Calzone') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Calzone') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Champignons') as i
union SELECT '1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Calzone') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Oeuf') as i);
-- Rucola
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Rucola') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Rucola') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Rucola') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Rucola') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Rucola') as i);
-- Saumon
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Saumon') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Saumon') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Saumon') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '100',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Saumon') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Saumon') as i);
-- Capres
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Capres') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Capres') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Capres') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '100',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='Capres') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Capres') as i);
-- 4 Saisons
INSERT INTO ocpizza.recette (quantite_recette, id_pizza, id_ingredient) (SELECT '0.2',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Pâte') as i
union SELECT '0.4',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Sauce Tomates') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Fromage rapé') as i
union SELECT '100',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Capres') as i
union SELECT '100',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Champignons') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Salami') as i
union SELECT '0.1',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Gorgonzola') as i
union SELECT '70',p.id_pizza,i.id_ingredient from (select id_pizza from ocpizza.pizza WHERE nom_pizza='4 Saisons') as p cross join (SELECT id_ingredient from ocpizza.ingredient where nom_ingredient='Courgette') as i);


-- Commandes
-- En cours
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_vendeur,id_adresse) (SELECT 'en cours','21.02.2019','21','1',p.id_employee,v.id_employee,'1' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Vendeur' order by random() limit 1) as v);
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_livreur,id_adresse) (SELECT 'en cours','21.02.2019','6','3',p.id_employee,v.id_employee,'12' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Livreur' order by random() limit 1) as v);
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_vendeur,id_livreur,id_adresse) (SELECT 'en cours','21.02.2019','17','2',p.id_employee,v.id_employee,l.id_employee,'20' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Vendeur' order by random() limit 1) as v cross join (select id_employee from ocpizza.employe where type_employee='Livreur' order by random() limit 1) as l);
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_vendeur,id_livreur,id_adresse) (SELECT 'en cours','21.02.2019','5','4',p.id_employee,v.id_employee,l.id_employee,'8' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Vendeur' order by random() limit 1) as v cross join (select id_employee from ocpizza.employe where type_employee='Livreur' order by random() limit 1) as l);
-- Passée
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_vendeur,id_adresse) (SELECT 'passee','12.02.2019','12','1',p.id_employee,v.id_employee,'1' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Vendeur' order by random() limit 1) as v);
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_livreur,id_adresse) (SELECT 'passee','13.02.2019','8','3',p.id_employee,v.id_employee,'12' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Livreur' order by random() limit 1) as v);
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_vendeur,id_livreur,id_adresse) (SELECT 'en cours','21.02.2019','12','2',p.id_employee,v.id_employee,l.id_employee,'20' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Vendeur' order by random() limit 1) as v cross join (select id_employee from ocpizza.employe where type_employee='Livreur' order by random() limit 1) as l);
INSERT INTO ocpizza.commande (statut_commande,date_commande,prix_commande,id_client,id_pizzaiolo,id_vendeur,id_livreur,id_adresse) (SELECT 'en cours','21.02.2019','19.5','1',p.id_employee,v.id_employee,l.id_employee,'1' from (select id_employee from ocpizza.employe where type_employee='Pizzaiolo' order by random() limit 1) as p cross join (select id_employee from ocpizza.employe where type_employee='Vendeur' order by random() limit 1) as v cross join (select id_employee from ocpizza.employe where type_employee='Livreur' order by random() limit 1) as l);

-- Panier
INSERT INTO ocpizza.panier (id_commande,id_pizza,quantite_pizza) VALUES ('1','1','3'),('1','4','1'),('2','4','1'),('3','7','2'),('4','1','1'),('5','3','2'),('6','6','1'),('7','4','2'),('8','3','4');
